// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzHgNt1bayH5MOjos9HI8cowvnp2WOnGI',
    appId: '1:990621141740:web:1c54d5ddfeb234e6d973c9',
    messagingSenderId: '990621141740',
    projectId: 'color-filter-7f59c',
    authDomain: 'color-filter-7f59c.firebaseapp.com',
    databaseURL: 'https://color-filter-7f59c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'color-filter-7f59c.firebasestorage.app',
    measurementId: 'G-QK5HKECDLM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaMdmLzOyg2zFN4KSv1Tnuhd8EHzfQxZY',
    appId: '1:990621141740:android:292d574cb2959c21d973c9',
    messagingSenderId: '990621141740',
    projectId: 'color-filter-7f59c',
    databaseURL: 'https://color-filter-7f59c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'color-filter-7f59c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDh6cyw5EHcEzy6eVB0XE1AOnpqSMwDS5k',
    appId: '1:990621141740:ios:d6c7ba3168992b13d973c9',
    messagingSenderId: '990621141740',
    projectId: 'color-filter-7f59c',
    databaseURL: 'https://color-filter-7f59c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'color-filter-7f59c.firebasestorage.app',
    iosBundleId: 'com.example.imageEditing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDh6cyw5EHcEzy6eVB0XE1AOnpqSMwDS5k',
    appId: '1:990621141740:ios:d6c7ba3168992b13d973c9',
    messagingSenderId: '990621141740',
    projectId: 'color-filter-7f59c',
    databaseURL: 'https://color-filter-7f59c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'color-filter-7f59c.firebasestorage.app',
    iosBundleId: 'com.example.imageEditing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzHgNt1bayH5MOjos9HI8cowvnp2WOnGI',
    appId: '1:990621141740:web:d8428f842f32b7cbd973c9',
    messagingSenderId: '990621141740',
    projectId: 'color-filter-7f59c',
    authDomain: 'color-filter-7f59c.firebaseapp.com',
    databaseURL: 'https://color-filter-7f59c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'color-filter-7f59c.firebasestorage.app',
    measurementId: 'G-LJSHKYKB38',
  );
}
